#include "board.h"
#include "driver/adc.h"
#include "driver/backlight.h"
#include "driver/crc.h"
#include "driver/gpio.h"
#include "driver/st7565.h"
#include "driver/uart.h"
#include "inc/dp32g030/gpio.h"
#include "inc/dp32g030/portcon.h"
#include "inc/dp32g030/saradc.h"
#include "inc/dp32g030/syscon.h"

// Макросы для сокращения кода
#define SET_BITS(reg, mask) ((reg) |= (mask))
#define CLEAR_BITS(reg, mask) ((reg) &= ~(mask))
#define MODIFY_REG(reg, clear, set)                                            \
  do {                                                                         \
    (reg) = ((reg) & ~(clear)) | (set);                                        \
  } while (0)

// Константы для часто используемых масок (вычисляются на этапе компиляции)
#define GPIOA_DIR_OUTPUT_MASK                                                  \
  (GPIO_DIR_10_BITS_OUTPUT | GPIO_DIR_11_BITS_OUTPUT |                         \
   GPIO_DIR_12_BITS_OUTPUT | GPIO_DIR_13_BITS_OUTPUT)

#define GPIOA_DIR_INPUT_MASK                                                   \
  (GPIO_DIR_3_MASK | GPIO_DIR_4_MASK | GPIO_DIR_5_MASK | GPIO_DIR_6_MASK)

#define GPIOB_DIR_OUTPUT_MASK                                                  \
  (GPIO_DIR_6_BITS_OUTPUT | GPIO_DIR_9_BITS_OUTPUT | GPIO_DIR_11_BITS_OUTPUT | \
   GPIO_DIR_15_BITS_OUTPUT)

#define GPIOC_DIR_OUTPUT_MASK                                                  \
  (GPIO_DIR_0_BITS_OUTPUT | GPIO_DIR_1_BITS_OUTPUT | GPIO_DIR_2_BITS_OUTPUT |  \
   GPIO_DIR_3_BITS_OUTPUT | GPIO_DIR_4_BITS_OUTPUT)

#define GPIOC_DIR_INPUT_MASK (GPIO_DIR_5_MASK)

void BOARD_GPIO_Init(void) {
  // GPIO A configuration - одна операция на регистр
  SET_BITS(GPIOA->DIR, GPIOA_DIR_OUTPUT_MASK);
  CLEAR_BITS(GPIOA->DIR, GPIOA_DIR_INPUT_MASK);

  // GPIO B configuration
  SET_BITS(GPIOB->DIR, GPIOB_DIR_OUTPUT_MASK);

  // GPIO C configuration
  SET_BITS(GPIOC->DIR, GPIOC_DIR_OUTPUT_MASK);
  CLEAR_BITS(GPIOC->DIR, GPIOC_DIR_INPUT_MASK);
}

void BOARD_PORTCON_Init(void) {
  // PORT A pin selection - сгруппированные операции
  MODIFY_REG(PORTCON_PORTA_SEL0,
             PORTCON_PORTA_SEL0_A3_MASK | PORTCON_PORTA_SEL0_A4_MASK |
                 PORTCON_PORTA_SEL0_A5_MASK | PORTCON_PORTA_SEL0_A6_MASK,
             PORTCON_PORTA_SEL0_A3_BITS_GPIOA3 |
                 PORTCON_PORTA_SEL0_A4_BITS_GPIOA4 |
                 PORTCON_PORTA_SEL0_A5_BITS_GPIOA5 |
                 PORTCON_PORTA_SEL0_A6_BITS_GPIOA6 |
                 PORTCON_PORTA_SEL0_A7_BITS_UART1_TX);

  MODIFY_REG(PORTCON_PORTA_SEL1,
             PORTCON_PORTA_SEL1_A10_MASK | PORTCON_PORTA_SEL1_A11_MASK |
                 PORTCON_PORTA_SEL1_A12_MASK | PORTCON_PORTA_SEL1_A13_MASK,
             PORTCON_PORTA_SEL1_A8_BITS_UART1_RX |
                 PORTCON_PORTA_SEL1_A9_BITS_SARADC_CH4 |
                 PORTCON_PORTA_SEL1_A10_BITS_GPIOA10 |
                 PORTCON_PORTA_SEL1_A11_BITS_GPIOA11 |
                 PORTCON_PORTA_SEL1_A12_BITS_GPIOA12 |
                 PORTCON_PORTA_SEL1_A13_BITS_GPIOA13 |
                 PORTCON_PORTA_SEL1_A14_BITS_SARADC_CH9);

  // PORT B pin selection
  MODIFY_REG(PORTCON_PORTB_SEL0,
             PORTCON_PORTB_SEL0_B6_MASK | PORTCON_PORTB_SEL0_B7_MASK,
             PORTCON_PORTB_SEL0_B6_BITS_GPIOB6 |
                 PORTCON_PORTB_SEL0_B7_BITS_SPI0_SSN);

  MODIFY_REG(PORTCON_PORTB_SEL1,
             PORTCON_PORTB_SEL1_B9_MASK | PORTCON_PORTB_SEL1_B11_MASK |
                 PORTCON_PORTB_SEL1_B14_MASK | PORTCON_PORTB_SEL1_B15_MASK,
             PORTCON_PORTB_SEL1_B8_BITS_SPI0_CLK |
                 PORTCON_PORTB_SEL1_B9_BITS_GPIOB9 |
                 PORTCON_PORTB_SEL1_B10_BITS_SPI0_MOSI |
                 PORTCON_PORTB_SEL1_B11_BITS_GPIOB11);

  // PORT C pin selection
  CLEAR_BITS(PORTCON_PORTC_SEL0,
             PORTCON_PORTC_SEL0_C0_MASK | PORTCON_PORTC_SEL0_C1_MASK |
                 PORTCON_PORTC_SEL0_C2_MASK | PORTCON_PORTC_SEL0_C3_MASK |
                 PORTCON_PORTC_SEL0_C4_MASK | PORTCON_PORTC_SEL0_C5_MASK);

  // PORT A configuration - объединенные константы
  static const uint32_t PORTA_IE_ENABLE =
      PORTCON_PORTA_IE_A3_BITS_ENABLE | PORTCON_PORTA_IE_A4_BITS_ENABLE |
      PORTCON_PORTA_IE_A5_BITS_ENABLE | PORTCON_PORTA_IE_A6_BITS_ENABLE |
      PORTCON_PORTA_IE_A8_BITS_ENABLE;

  static const uint32_t PORTA_IE_DISABLE =
      PORTCON_PORTA_IE_A10_MASK | PORTCON_PORTA_IE_A11_MASK |
      PORTCON_PORTA_IE_A12_MASK | PORTCON_PORTA_IE_A13_MASK;

  SET_BITS(PORTCON_PORTA_IE, PORTA_IE_ENABLE);
  CLEAR_BITS(PORTCON_PORTA_IE, PORTA_IE_DISABLE);

  // Pull-up configuration
  static const uint32_t PORTA_PU_ENABLE =
      PORTCON_PORTA_PU_A3_BITS_ENABLE | PORTCON_PORTA_PU_A4_BITS_ENABLE |
      PORTCON_PORTA_PU_A5_BITS_ENABLE | PORTCON_PORTA_PU_A6_BITS_ENABLE;

  static const uint32_t PORTA_PU_DISABLE =
      PORTCON_PORTA_PU_A10_MASK | PORTCON_PORTA_PU_A11_MASK |
      PORTCON_PORTA_PU_A12_MASK | PORTCON_PORTA_PU_A13_MASK;

  SET_BITS(PORTCON_PORTA_PU, PORTA_PU_ENABLE);
  CLEAR_BITS(PORTCON_PORTA_PU, PORTA_PU_DISABLE);

  // Pull-down configuration
  static const uint32_t PORTA_PD_DISABLE =
      PORTCON_PORTA_PD_A3_MASK | PORTCON_PORTA_PD_A4_MASK |
      PORTCON_PORTA_PD_A5_MASK | PORTCON_PORTA_PD_A6_MASK |
      PORTCON_PORTA_PD_A10_MASK | PORTCON_PORTA_PD_A11_MASK |
      PORTCON_PORTA_PD_A12_MASK | PORTCON_PORTA_PD_A13_MASK;

  CLEAR_BITS(PORTCON_PORTA_PD, PORTA_PD_DISABLE);

  // Open-drain configuration
  static const uint32_t PORTA_OD_ENABLE =
      PORTCON_PORTA_OD_A3_BITS_ENABLE | PORTCON_PORTA_OD_A4_BITS_ENABLE |
      PORTCON_PORTA_OD_A5_BITS_ENABLE | PORTCON_PORTA_OD_A6_BITS_ENABLE;

  static const uint32_t PORTA_OD_DISABLE =
      PORTCON_PORTA_OD_A10_MASK | PORTCON_PORTA_OD_A11_MASK |
      PORTCON_PORTA_OD_A12_MASK | PORTCON_PORTA_OD_A13_MASK;

  SET_BITS(PORTCON_PORTA_OD, PORTA_OD_ENABLE);
  CLEAR_BITS(PORTCON_PORTA_OD, PORTA_OD_DISABLE);

  // PORT B configuration
  SET_BITS(PORTCON_PORTB_IE, PORTCON_PORTB_IE_B14_BITS_ENABLE);
  CLEAR_BITS(PORTCON_PORTB_IE,
             PORTCON_PORTB_IE_B6_MASK | PORTCON_PORTB_IE_B7_MASK |
                 PORTCON_PORTB_IE_B8_MASK | PORTCON_PORTB_IE_B9_MASK |
                 PORTCON_PORTB_IE_B10_MASK | PORTCON_PORTB_IE_B11_MASK |
                 PORTCON_PORTB_IE_B15_MASK);

  static const uint32_t PORTB_COMMON_DISABLE =
      PORTCON_PORTB_PU_B6_MASK | PORTCON_PORTB_PU_B9_MASK |
      PORTCON_PORTB_PU_B11_MASK | PORTCON_PORTB_PU_B14_MASK |
      PORTCON_PORTB_PU_B15_MASK;

  CLEAR_BITS(PORTCON_PORTB_PU, PORTB_COMMON_DISABLE);
  CLEAR_BITS(PORTCON_PORTB_PD, PORTB_COMMON_DISABLE);

  CLEAR_BITS(PORTCON_PORTB_OD,
             PORTCON_PORTB_OD_B6_MASK | PORTCON_PORTB_OD_B9_MASK |
                 PORTCON_PORTB_OD_B11_MASK | PORTCON_PORTB_OD_B15_MASK);
  SET_BITS(PORTCON_PORTB_OD, PORTCON_PORTB_OD_B14_BITS_ENABLE);

  // PORT C configuration
  SET_BITS(PORTCON_PORTC_IE, PORTCON_PORTC_IE_C5_BITS_ENABLE);
  CLEAR_BITS(PORTCON_PORTC_IE,
             PORTCON_PORTC_IE_C0_MASK | PORTCON_PORTC_IE_C1_MASK |
                 PORTCON_PORTC_IE_C2_MASK | PORTCON_PORTC_IE_C3_MASK |
                 PORTCON_PORTC_IE_C4_MASK);

  SET_BITS(PORTCON_PORTC_PU, PORTCON_PORTC_PU_C5_BITS_ENABLE);

  static const uint32_t PORTC_COMMON_DISABLE =
      PORTCON_PORTC_PU_C0_MASK | PORTCON_PORTC_PU_C1_MASK |
      PORTCON_PORTC_PU_C2_MASK | PORTCON_PORTC_PU_C3_MASK |
      PORTCON_PORTC_PU_C4_MASK;

  CLEAR_BITS(PORTCON_PORTC_PU, PORTC_COMMON_DISABLE);
  CLEAR_BITS(PORTCON_PORTC_PD, PORTC_COMMON_DISABLE | PORTCON_PORTC_PD_C5_MASK);
  CLEAR_BITS(PORTCON_PORTC_OD, PORTC_COMMON_DISABLE);

  SET_BITS(
      PORTCON_PORTC_OD,
      PORTCON_PORTC_OD_C0_BITS_DISABLE | PORTCON_PORTC_OD_C1_BITS_DISABLE |
          PORTCON_PORTC_OD_C2_BITS_DISABLE | PORTCON_PORTC_OD_C3_BITS_DISABLE |
          PORTCON_PORTC_OD_C4_BITS_DISABLE | PORTCON_PORTC_OD_C5_BITS_ENABLE);
}

void BOARD_ADC_Init(void) {
  // Использование designated initializers для ясности
  ADC_Config_t Config = {
      .CLK_SEL = SYSCON_CLK_SEL_W_SARADC_SMPL_VALUE_DIV2,
      .CH_SEL = ADC_CH4 | ADC_CH9,
      .AVG = SARADC_CFG_AVG_VALUE_8_SAMPLE,
      .CONT = SARADC_CFG_CONT_VALUE_SINGLE,
      .MEM_MODE = SARADC_CFG_MEM_MODE_VALUE_CHANNEL,
      .SMPL_CLK = SARADC_CFG_SMPL_CLK_VALUE_INTERNAL,
      .SMPL_SETUP = SARADC_CFG_SMPL_SETUP_VALUE_1_CYCLE,
      .SMPL_WIN = SARADC_CFG_SMPL_WIN_VALUE_15_CYCLE,
      .ADC_TRIG = SARADC_CFG_ADC_TRIG_VALUE_CPU,
      .CALIB_OFFSET_VALID = SARADC_CALIB_OFFSET_VALID_VALUE_YES,
      .CALIB_KD_VALID = SARADC_CALIB_KD_VALID_VALUE_YES,
      .DMA_EN = SARADC_CFG_DMA_EN_VALUE_DISABLE,
      .IE_CHx_EOC = SARADC_IE_CHx_EOC_VALUE_NONE,
      .IE_FIFO_HFULL = SARADC_IE_FIFO_HFULL_VALUE_DISABLE,
      .IE_FIFO_FULL = SARADC_IE_FIFO_FULL_VALUE_DISABLE,
  };

  ADC_Configure(&Config);
  ADC_Enable();
  ADC_SoftReset();
}

void BOARD_ADC_GetBatteryInfo(uint16_t *pVoltage, uint16_t *pCurrent) {
  ADC_Start();

  // Добавлен таймаут для защиты от зависания
  uint32_t timeout = 100000;
  while (!ADC_CheckEndOfConversion(ADC_CH9) && --timeout)
    ;

  // Даже если таймаут, читаем значения (могут быть невалидными)
  *pVoltage = ADC_GetValue(ADC_CH4);
  *pCurrent = ADC_GetValue(ADC_CH9);
}

// Inline функции для частых операций (могут быть в .h)
void BOARD_ToggleGreen(bool on) {
  BK4819_ToggleGpioOut(BK4819_GPIO0_PIN28_GREEN, on);
}

void BOARD_ToggleRed(bool on) {
  BK4819_ToggleGpioOut(BK4819_GPIO5_PIN1_RED, on);
}

void BOARD_Init(void) {
  // Можно добавить инициализацию если нужно
}
